---
- hosts: all
  gather_facts: false

  tasks:
    - name: 'Create PS Conf EU 2022 demo file'
      pauby.psconfeu2022.win_psconfeu2022_file:
        name: 'psconfeu2022_test'
        state: 'absent'